kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ghost-0
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "172.18.0.0/16"
  disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
