CREATE TABLE u_data (
  userid INT,
  movieid INT,
  rating INT,
  unixtime STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH '/tmp/u.data'
OVERWRITE INTO TABLE u_data;

SELECT COUNT(*) FROM u_data;

CREATE TABLE u_data_orc 
STORED AS ORC
AS
SELECT * FROM u_data;

SELECT COUNT(*) FROM u_data_orc;