# When using local volumes, it is recommended to create
# a StorageClass with volumeBindingMode set to
# WaitForFirstConsumer. Delaying volume binding ensures
# that the PersistentVolumeClaim binding decision will
# also be evaluated with any other node constraints the
# pod may have, such as node resource requirements,
# node selectors, pod affinity, and pod anti-affinity.
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
# Supported policies: Delete, Retain
reclaimPolicy: Delete
